import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import type { AppConfig, DailyReport, TrendingRepo } from "../types/index.js";

function escapeMarkdown(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function formatStars(n: number): string {
  return n >= 1000 ? `${(n / 1000).toFixed(1)}k` : String(n);
}

function generateHighlightsSection(repos: TrendingRepo[]): string {
  if (repos.length === 0) return "";

  const lines: string[] = [
    "## AI/Agent Highlights\n",
    "> Repositories related to AI, Agents, LLM, Knowledge-Base, RAG, MCP\n",
    "| Repository | Description | Language | Stars | Today | Topics |",
    "|---|---|---|---|---|---|",
  ];

  for (const repo of repos) {
    const link = `[${repo.fullName}](${repo.url})`;
    const desc = escapeMarkdown(repo.description).slice(0, 80);
    const topics = repo.topics.slice(0, 5).map((t) => `\`${t}\``).join(" ");
    lines.push(
      `| ${link} | ${desc} | ${repo.language} | ${formatStars(repo.stars)} | +${repo.starsToday} | ${topics} |`
    );
  }

  return lines.join("\n") + "\n";
}

function generateSection(
  title: string,
  repos: TrendingRepo[],
  showLanguage: boolean
): string {
  const lines: string[] = [`## ${title}\n`];

  const header = showLanguage
    ? "| # | Repository | Description | Language | Stars | Today |"
    : "| # | Repository | Description | Stars | Today |";
  const separator = showLanguage
    ? "|---|---|---|---|---|---|"
    : "|---|---|---|---|---|";

  lines.push(header, separator);

  repos.forEach((repo, i) => {
    const link = `[${repo.fullName}](${repo.url})`;
    const desc = escapeMarkdown(repo.description).slice(0, 80);
    if (showLanguage) {
      lines.push(
        `| ${i + 1} | ${link} | ${desc} | ${repo.language} | ${formatStars(repo.stars)} | +${repo.starsToday} |`
      );
    } else {
      lines.push(
        `| ${i + 1} | ${link} | ${desc} | ${formatStars(repo.stars)} | +${repo.starsToday} |`
      );
    }
  });

  return lines.join("\n") + "\n";
}

export function generateMarkdown(report: DailyReport, config: AppConfig): string {
  const parts: string[] = [];

  // Header
  parts.push(`# GitHub Trending Daily Report - ${report.date}\n`);
  parts.push(
    `> Auto-generated by [GitHub Trend Robot](https://github.com/trending)\n`
  );
  parts.push("---\n");

  // AI/Agent Highlights
  const highlightMd = generateHighlightsSection(report.highlights);
  if (highlightMd) {
    parts.push(highlightMd);
    parts.push("---\n");
  }

  // Language sections
  for (const section of report.sections) {
    parts.push(generateSection(section.title, section.repos, section.language === ""));
    parts.push("---\n");
  }

  // Footer
  const languages = config.languages.map((l) => l || "overall").join(", ");
  parts.push(
    `*Generated at ${new Date().toISOString()} | Config: languages=${languages} since=${config.since}*`
  );

  return parts.join("\n");
}

export function saveReport(
  report: DailyReport,
  config: AppConfig
): string {
  const outputDir = resolve(process.cwd(), config.outputDir);
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  const markdown = generateMarkdown(report, config);
  const filePath = resolve(outputDir, `${report.date}.md`);
  writeFileSync(filePath, markdown, "utf-8");

  console.log(`Report saved to: ${filePath}`);
  return filePath;
}
